### ISSUE TITLE
INFO:__main__:still waiting on FFmpeg...

### ISSUE THREAD

**Issue by Yaque** [Allong12/py-scrcpy#4]
But i show i hava add ffmpeg into path.

the version ffmpeg-20190207-7cab547-win64-shared

can you show more message ?

**Comment by Yaque** [comment]
ok, i kown why.foolish for me.
just need use our phone.

but i don't kown why. The effect is very poor。

**Comment by M6D6M6A** [comment]
Opened up 1 Time, but quit after like 15s with error, since then its allways showing this error:

INFO:__main__:START STDERR THREAD
INFO:__main__:START STDIN THREAD
INFO:__main__:START STDOUT THREAD
INFO:__main__:Waiting on FFmpeg to detect source
INFO:__main__:still waiting on FFmpeg...
INFO:__main__:still waiting on FFmpeg...
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/scrcpy/1.8/bin/scrcpy_client.py", line 90, in stdin_thread
    data = self.sock.recv(frm_len)
OSError: [Errno 22] Invalid argument

Any Ideas?

**Comment by deepanrajm** [comment]
Any updates on this issue ? i am getting the same error
